In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,6])

array([1, 2, 3, 4, 6])

In [3]:
type(np.array([1,2,3,4,6]))

numpy.ndarray

In [4]:
np.array([1,2,3,4,6,'sudh','(4+4j)'])

array(['1', '2', '3', '4', '6', 'sudh', '(4+4j)'], dtype='<U11')

In [5]:
np.array([1,2,3,4,4.5,6.0])

array([1. , 2. , 3. , 4. , 4.5, 6. ])

In [6]:
np.array([[1,3],[3,4]])

array([[1, 3],
       [3, 4]])

In [7]:
np.array([[1,3],[3,4],[6,7,8]])

<ipython-input-7-2fc331c0f648>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[3,4],[6,7,8]])


array([list([1, 3]), list([3, 4]), list([6, 7, 8])], dtype=object)

In [8]:
np.array([[1,3],[3,4],[6,7]])

array([[1, 3],
       [3, 4],
       [6, 7]])

In [9]:
np.array([[[1,3],[2,4]],[[1,3],[2,4]]])

array([[[1, 3],
        [2, 4]],

       [[1, 3],
        [2, 4]]])

In [11]:
np.array([1,2,3],ndmin=4)# No of dimension

array([[[[1, 2, 3]]]])

In [12]:
np.array([1,2,3],dtype=complex)# Convert all the data in complex

array([1.+0.j, 2.+0.j, 3.+0.j])

In [13]:
# all element of different data tyoess
arr=np.array([(1,2),(4,5)],dtype=[('a','<i2'),('b','<i8')])

In [14]:
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [15]:
arr[0][0]

1

In [16]:
type(arr[0][0])

numpy.int16

In [17]:
type(arr[0][1])

numpy.int64

In [18]:
   np.mat(arr)

matrix([[(1, 2), (4, 5)]], dtype=[('a', '<i2'), ('b', '<i8')])

In [19]:
arr=np.array([[1,2],[2,3]])

In [26]:
# Create Matrix
mat=np.mat(arr)

In [21]:
l=[3,4,5,6,7]

In [22]:
np.array(l)# Converrt list into array

array([3, 4, 5, 6, 7])

In [23]:
np.asarray(l)# Cinvert list into array

array([3, 4, 5, 6, 7])

In [24]:
np.asanyarray(l)# Convert list into array

array([3, 4, 5, 6, 7])

In [27]:
np.asanyarray(mat)# as matrix is a type of array only so it  will noyt   convert

matrix([[1, 2],
        [2, 3]])

In [28]:
np.asarray(mat)# it will not check and directy convert it into array

array([[1, 2],
       [2, 3]])

In [29]:
np.asanyarray(mat)# it will check whether array ifyes than no need to convert  )

matrix([[1, 2],
        [2, 3]])

In [31]:
issubclass(np.matrix,np.ndarray)# it will check whether matrux is subclass of ndarray

True

In [32]:
arr

array([[1, 2],
       [2, 3]])

In [33]:
a=arr# it will get yupdated when value is cahnged for arr

In [34]:
b=np.copy(arr)#it will not get updated when value is changed for arr

In [35]:
arr[0][0]=67# array is mutable

In [36]:
a

array([[67,  2],
       [ 2,  3]])

In [37]:
b

array([[1, 2],
       [2, 3]])

In [38]:
for i in a:
    print(i)

[67  2]
[2 3]


In [39]:
for i in a:
    for j in i:
        print(j)

67
2
2
3


In [40]:
np.fromfunction(lambda i,j :i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [41]:
np.fromfunction(lambda i,j:i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [42]:
np.fromfunction(lambda i,j:i**j,(3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [43]:
np.fromfunction(lambda i,j:i/j,(3,3))

<ipython-input-43-5c31f1d2ce4a>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i,j:i/j,(3,3))
<ipython-input-43-5c31f1d2ce4a>:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i,j:i/j,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [44]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [48]:
gen=(i*i for i in range(5))

In [46]:
def test(x):
    yield x

In [47]:
test(5)

<generator object test at 0x000001314D3ACDD0>

In [49]:
np.fromiter(gen,dtype=int)

array([ 0,  1,  4,  9, 16])

In [51]:
np.fromiter(range(5),dtype=int)

array([0, 1, 2, 3, 4])

In [56]:
np.fromstring('1,2,3,4,5,6',sep=',',dtype=int)

array([1, 2, 3, 4, 5, 6])

In [57]:
np.fromstring('12 32 43 56 76 67 78 878',sep=' ',dtype=int)

array([ 12,  32,  43,  56,  76,  67,  78, 878])

In [59]:
l=[1,2,4,5,6,7]
arr=np.array(l)

In [63]:
arr1=np.array([[1,2,3,4],[2,3,4,5],[4,5,6,7]])

In [64]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [65]:
type(arr1)

numpy.ndarray

In [66]:
arr1.ndim# givs the dmension of the array

2

In [67]:
arr1.size# total element is the array

12

In [68]:
arr1.shape#n*m rows*columns

(3, 4)

In [69]:
arr1.dtype


dtype('int32')

In [70]:
arr2=np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])

In [71]:
arr2

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [73]:
arr2.size

16

In [74]:
arr2.shape

(2, 2, 4)

In [75]:
arr2.ndim

3

In [78]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [79]:
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [81]:
np.arange(6.6,9)

array([6.6, 7.6, 8.6])

In [84]:
np.arange(9,6.6,-.3)#

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [85]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [93]:
np.linspace(3,8)# in between line fifty points by default

array([3.        , 3.10204082, 3.20408163, 3.30612245, 3.40816327,
       3.51020408, 3.6122449 , 3.71428571, 3.81632653, 3.91836735,
       4.02040816, 4.12244898, 4.2244898 , 4.32653061, 4.42857143,
       4.53061224, 4.63265306, 4.73469388, 4.83673469, 4.93877551,
       5.04081633, 5.14285714, 5.24489796, 5.34693878, 5.44897959,
       5.55102041, 5.65306122, 5.75510204, 5.85714286, 5.95918367,
       6.06122449, 6.16326531, 6.26530612, 6.36734694, 6.46938776,
       6.57142857, 6.67346939, 6.7755102 , 6.87755102, 6.97959184,
       7.08163265, 7.18367347, 7.28571429, 7.3877551 , 7.48979592,
       7.59183673, 7.69387755, 7.79591837, 7.89795918, 8.        ])

In [94]:
np.linspace(3,8,5)# in between line five datasete

array([3.  , 4.25, 5.5 , 6.75, 8.  ])

In [95]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [97]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [98]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [99]:
np.ones(4)

array([1., 1., 1., 1.])

In [100]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [101]:
np.empty(4)

array([1., 1., 1., 1.])

In [102]:
np.empty((2,3))

array([[1., 2., 3.],
       [4., 5., 6.]])

In [106]:
np.empty((4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [108]:
np.eye(3)#identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [110]:
np.linspace(2,4,4)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [111]:
np.linspace(2,4,4,endpoint=False)

array([2. , 2.5, 3. , 3.5])

In [115]:
np.linspace(2,4,4,endpoint=False,axis=0)

array([2. , 2.5, 3. , 3.5])

In [117]:
np.linspace([1,4],4,endpoint=False,axis=1)

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  ]])

In [124]:
np.logspace([2],[3],axis=1)

array([[ 100.        ,  104.81131342,  109.8541142 ,  115.13953993,
         120.67926406,  126.48552169,  132.57113656,  138.94954944,
         145.63484775,  152.64179672,  159.98587196,  167.68329368,
         175.75106249,  184.20699693,  193.06977289,  202.35896477,
         212.09508879,  222.29964825,  232.99518105,  244.20530945,
         255.95479227,  268.26957953,  281.1768698 ,  294.70517026,
         308.88435965,  323.74575428,  339.32217719,  355.64803062,
         372.75937203,  390.69399371,  409.49150624,  429.19342601,
         449.8432669 ,  471.48663635,  494.17133613,  517.94746792,
         542.86754393,  568.9866029 ,  596.36233166,  625.05519253,
         655.12855686,  686.648845  ,  719.685673  ,  754.31200634,
         790.60432109,  828.64277285,  868.51137375,  910.29817799,
         954.09547635, 1000.        ]])

In [125]:
d=np.linspace(4,7,40)

In [126]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [127]:
d.ndim

1

In [128]:
d.shape

(40,)

In [129]:
d.size

40

In [131]:
d.reshape(40,1)# Reshape the dataarray

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [133]:
d.reshape(2,20)

array([[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
        4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
        4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
        5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
       [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
        5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
        6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
        6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]])

In [134]:
d.reshape(2,1,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [135]:
d.reshape(1,4,10)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [140]:
# Generate random data
np.random.rand(3)# it will create data random based on guassian distribution/normal distribution meand and sd can be anything 

array([0.95213313, 0.33648607, 0.64492296])

In [141]:
np.random.randn(5)
# it returns from Standard Normal deviatin  means sd=1 mean=0

array([ 0.21313582,  0.79795053, -0.21776215, -0.29220364,  0.86305199])

In [142]:
np.random.randn(3,4)

array([[ 1.12167926, -0.14384904, -0.06281662, -0.6233329 ],
       [ 1.81112684,  0.65193248, -0.24552454, -1.11928364],
       [ 0.99235017, -2.20014554, -1.78816729,  0.26763176]])

In [143]:
np.random.randn(2,2,3)

array([[[-0.39579974, -1.29196182,  0.92864696],
        [ 0.7063511 , -0.43240708,  0.11198207]],

       [[ 0.02558356, -0.02623503, -1.60024729],
        [ 0.11309697, -0.44244254,  0.70462953]]])

In [148]:
np.random.randint(5)# it will give random interger below 5

0

In [165]:
np.random.randint(5,10)# Data between this range

7

In [166]:
np.random.randint(5,60,(4,4))

array([[26, 53, 21, 32],
       [50, 32, 50, 44],
       [39, 59, 52, 19],
       [53, 44, 38, 13]])

In [169]:
arr=np.random.randint(3,9,(3,3))# Create an array with eement between 3, 9 abd 3*3 

In [170]:
arr

array([[8, 4, 6],
       [6, 3, 3],
       [8, 3, 6]])

In [171]:
arr.reshape(1,9)

array([[8, 4, 6, 6, 3, 3, 8, 3, 6]])

In [172]:
arr.reshape(9,1)

array([[8],
       [4],
       [6],
       [6],
       [3],
       [3],
       [8],
       [3],
       [6]])

In [173]:
arr.reshape(1,1,9)

array([[[8, 4, 6, 6, 3, 3, 8, 3, 6]]])

In [174]:
arr.reshape(3,3,1)

array([[[8],
        [4],
        [6]],

       [[6],
        [3],
        [3]],

       [[8],
        [3],
        [6]]])

In [178]:
arr.reshape(3,-1)# if negative value then it will take autmoatically from negative value

array([[8, 4, 6],
       [6, 3, 3],
       [8, 3, 6]])

In [179]:
arr.max()# max element out of array

8

In [181]:
arr.min()

3

In [186]:
arr=np.random.randint(4,100,(5,5))# Create array 5*5

In [187]:
arr

array([[97, 83, 67, 90, 27],
       [76, 55, 61, 86, 13],
       [95, 56, 98, 78, 34],
       [92, 99, 82, 14, 79],
       [59, 56,  6, 35, 30]])

In [190]:
arr[3:,3:]

array([[14, 79],
       [35, 30]])

In [196]:
arr[:,[2,4]]# third and fifth column 

array([[67, 27],
       [61, 13],
       [98, 34],
       [82, 79],
       [ 6, 30]])

In [197]:
arr

array([[97, 83, 67, 90, 27],
       [76, 55, 61, 86, 13],
       [95, 56, 98, 78, 34],
       [92, 99, 82, 14, 79],
       [59, 56,  6, 35, 30]])

In [198]:
arr>10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True]])

In [200]:
arr[arr>10]# filter data where element is grter than 10 

array([97, 83, 67, 90, 27, 76, 55, 61, 86, 13, 95, 56, 98, 78, 34, 92, 99,
       82, 14, 79, 59, 56, 35, 30])

In [201]:
arr*arr

array([[9409, 6889, 4489, 8100,  729],
       [5776, 3025, 3721, 7396,  169],
       [9025, 3136, 9604, 6084, 1156],
       [8464, 9801, 6724,  196, 6241],
       [3481, 3136,   36, 1225,  900]])

In [202]:
arr1=np.random.randint(2,4,(3,3))

In [203]:
arr2=np.random.randint(2,4,(3,3))

In [205]:
arr1

array([[2, 2, 3],
       [3, 3, 2],
       [2, 2, 2]])

In [206]:
arr2

array([[3, 2, 2],
       [3, 2, 2],
       [2, 2, 2]])

In [207]:
arr1*arr2

array([[6, 4, 6],
       [9, 6, 4],
       [4, 4, 4]])

In [208]:
arr1@arr2# matrix multiplication

array([[18, 14, 14],
       [22, 16, 16],
       [16, 12, 12]])

In [209]:
arr1/0

<ipython-input-209-2e1dc0d9289f>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [210]:
arr1**2

array([[4, 4, 9],
       [9, 9, 4],
       [4, 4, 4]], dtype=int32)

In [211]:
# Broadcasting
arr=np.zeros((3,4))

In [212]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [214]:
a=np.array([1,2,3,4])

In [215]:
a

array([1, 2, 3, 4])

In [216]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [217]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [218]:
b=np.array([5,6,7])

In [220]:
b.reshape(3,1)+arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [221]:
b.T

array([5, 6, 7])

In [222]:
b

array([5, 6, 7])